<a href="https://colab.research.google.com/github/RaianaSeixas/teste/blob/main/ds_Aula06_Introdu%C3%A7%C3%A3o_Manipula%C3%A7%C3%A3o_de_Dados_Panda_ParteI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

# Pandas Series

In [ ]:
# Criando uma série em pandas
numeros = range(50, 70, 2)
numeros_serie = pd.Series(numeros)
print(numeros_serie)

0    50
1    52
2    54
3    56
4    58
5    60
6    62
7    64
8    66
9    68
dtype: int64


In [ ]:
type(numeros_serie)

pandas.core.series.Series

In [ ]:
numeros_serie.dtype

dtype('int64')

In [ ]:
# verificando index
numeros_serie[5]

np.int64(60)

In [ ]:
# Listando o index
numeros_serie.index

RangeIndex(start=0, stop=10, step=1)

In [ ]:
# Listando os valores
numeros_serie.values

array([50, 52, 54, 56, 58, 60, 62, 64, 66, 68])

In [ ]:
# Alterando o index
numeros_em_texto = ['primeiro','segundo','terceiro','quarto','quinto','sexto','sétimo','oitavo','nono','décimo']
numeros_serie_2 = pd.Series(numeros,index = numeros_em_texto)
numeros_serie_2

primeiro    50
segundo     52
terceiro    54
quarto      56
quinto      58
sexto       60
sétimo      62
oitavo      64
nono        66
décimo      68
dtype: int64

In [ ]:
# Convertendo index em coluna
numeros_serie_3 = numeros_serie_2.reset_index()
numeros_serie_3

index   0
0  primeiro  50
1   segundo  52
2  terceiro  54
3    quarto  56
4    quinto  58
5     sexto  60
6    sétimo  62
7    oitavo  64
8      nono  66
9    décimo  68

In [ ]:
# temos agora um Dataframe
type(numeros_serie_3)

pandas.core.frame.DataFrame

In [ ]:
numeros_serie_3.set_index('index')

0
index       
primeiro  50
segundo   52
terceiro  54
quarto    56
quinto    58
sexto     60
sétimo    62
oitavo    64
nono      66
décimo    68

In [ ]:
numeros_serie_3

index   0
0  primeiro  50
1   segundo  52
2  terceiro  54
3    quarto  56
4    quinto  58
5     sexto  60
6    sétimo  62
7    oitavo  64
8      nono  66
9    décimo  68

In [ ]:
numeros_serie_3 = numeros_serie_3.rename(columns={0: "numeros"})
numeros_serie_3

index  numeros
0  primeiro       50
1   segundo       52
2  terceiro       54
3    quarto       56
4    quinto       58
5     sexto       60
6    sétimo       62
7    oitavo       64
8      nono       66
9    décimo       68

# Dataframe

In [ ]:
modelos = ['A4 3.0 Quattro 4dr manual',
           'A4 3.0 Quattro 4dr auto',
           'A6 3.0 4dr',
           'A6 3.0 Quattro 4dr',
           'A4 3.0 convertible 2dr']

peso = [3583, 3627, 3561, 3880, 3814]

precos = ['$33,430', '$34,480', '$36,640', '$39,640', '$42,490']

In [ ]:
Autos_peso = pd.Series(peso,index=modelos)
Autos_preco = pd.Series(precos,index=modelos)

In [ ]:
Autos_preco

A4 3.0 Quattro 4dr manual    $33,430
A4 3.0 Quattro 4dr auto      $34,480
A6 3.0 4dr                   $36,640
A6 3.0 Quattro 4dr           $39,640
A4 3.0 convertible 2dr       $42,490
dtype: object

In [ ]:
Autos_peso

A4 3.0 Quattro 4dr manual    3583
A4 3.0 Quattro 4dr auto      3627
A6 3.0 4dr                   3561
A6 3.0 Quattro 4dr           3880
A4 3.0 convertible 2dr       3814
dtype: int64

In [ ]:
Autos = pd.DataFrame({'Peso':Autos_peso,'Preco':Autos_preco})
Autos

Peso    Preco
A4 3.0 Quattro 4dr manual  3583  $33,430
A4 3.0 Quattro 4dr auto    3627  $34,480
A6 3.0 4dr                 3561  $36,640
A6 3.0 Quattro 4dr         3880  $39,640
A4 3.0 convertible 2dr     3814  $42,490

In [ ]:
# Note que temos um dict
type({'Peso':Autos_peso,'Preco':Autos_preco})

dict

In [ ]:
Autos.index

Index(['A4 3.0 Quattro 4dr manual', 'A4 3.0 Quattro 4dr auto', 'A6 3.0 4dr',
       'A6 3.0 Quattro 4dr', 'A4 3.0 convertible 2dr'],
      dtype='object')

In [ ]:
Autos.columns

Index(['Peso', 'Preco'], dtype='object')

In [ ]:
Autos.values

array([[3583, '$33,430'],
       [3627, '$34,480'],
       [3561, '$36,640'],
       [3880, '$39,640'],
       [3814, '$42,490']], dtype=object)

In [ ]:
type(Autos.values)

numpy.ndarray

In [ ]:
Autos

Peso    Preco
A4 3.0 Quattro 4dr manual  3583  $33,430
A4 3.0 Quattro 4dr auto    3627  $34,480
A6 3.0 4dr                 3561  $36,640
A6 3.0 Quattro 4dr         3880  $39,640
A4 3.0 convertible 2dr     3814  $42,490

In [ ]:
# Informações do Dataframe
Autos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, A4 3.0 Quattro 4dr manual to A4 3.0 convertible 2dr
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Peso    5 non-null      int64 
 1   Preco   5 non-null      object
dtypes: int64(1), object(1)
memory usage: 292.0+ bytes


# Filtros

In [ ]:
Autos

Peso    Preco
A4 3.0 Quattro 4dr manual  3583  $33,430
A4 3.0 Quattro 4dr auto    3627  $34,480
A6 3.0 4dr                 3561  $36,640
A6 3.0 Quattro 4dr         3880  $39,640
A4 3.0 convertible 2dr     3814  $42,490

In [ ]:
# Seleção de coluna 1
Autos['Peso']

A4 3.0 Quattro 4dr manual    3583
A4 3.0 Quattro 4dr auto      3627
A6 3.0 4dr                   3561
A6 3.0 Quattro 4dr           3880
A4 3.0 convertible 2dr       3814
Name: Peso, dtype: int64

In [ ]:
# Seleção de coluna 2
Autos.Peso

A4 3.0 Quattro 4dr manual    3583
A4 3.0 Quattro 4dr auto      3627
A6 3.0 4dr                   3561
A6 3.0 Quattro 4dr           3880
A4 3.0 convertible 2dr       3814
Name: Peso, dtype: int64

In [ ]:
# Seleção de coluna 3
Autos.iloc[0:3,0:1]

Peso
A4 3.0 Quattro 4dr manual  3583
A4 3.0 Quattro 4dr auto    3627
A6 3.0 4dr                 3561

In [ ]:
# Seleção de coluna 4
Autos.loc['A4 3.0 Quattro 4dr manual':'A6 3.0 Quattro 4dr', "Peso"]

A4 3.0 Quattro 4dr manual    3583
A4 3.0 Quattro 4dr auto      3627
A6 3.0 4dr                   3561
A6 3.0 Quattro 4dr           3880
Name: Peso, dtype: int64

In [ ]:
Autos

Peso    Preco
A4 3.0 Quattro 4dr manual  3583  $33,430
A4 3.0 Quattro 4dr auto    3627  $34,480
A6 3.0 4dr                 3561  $36,640
A6 3.0 Quattro 4dr         3880  $39,640
A4 3.0 convertible 2dr     3814  $42,490

In [ ]:
# Adicionando uma coluna
Autos['PesoX2'] = Autos['Peso']*2
Autos

Peso    Preco  PesoX2
A4 3.0 Quattro 4dr manual  3583  $33,430    7166
A4 3.0 Quattro 4dr auto    3627  $34,480    7254
A6 3.0 4dr                 3561  $36,640    7122
A6 3.0 Quattro 4dr         3880  $39,640    7760
A4 3.0 convertible 2dr     3814  $42,490    7628

In [ ]:
# Selecionando mais de uma coluna por index
Autos.iloc[:,[0,2]]

Peso  PesoX2
A4 3.0 Quattro 4dr manual  3583    7166
A4 3.0 Quattro 4dr auto    3627    7254
A6 3.0 4dr                 3561    7122
A6 3.0 Quattro 4dr         3880    7760
A4 3.0 convertible 2dr     3814    7628

In [ ]:
Autos.values[:,0]

array([3583, 3627, 3561, 3880, 3814], dtype=object)

In [ ]:
Autos.values[:,0]

array([3583, 3627, 3561, 3880, 3814], dtype=object)

In [ ]:
Autos.loc['A4 3.0 Quattro 4dr auto',]

Peso         3627
Preco     $34,480
PesoX2       7254
Name: A4 3.0 Quattro 4dr auto, dtype: object

# Filtros lógicos

## --| >, <, <=, >=

In [ ]:
Autos

Peso    Preco  PesoX2
A4 3.0 Quattro 4dr manual  3583  $33,430    7166
A4 3.0 Quattro 4dr auto    3627  $34,480    7254
A6 3.0 4dr                 3561  $36,640    7122
A6 3.0 Quattro 4dr         3880  $39,640    7760
A4 3.0 convertible 2dr     3814  $42,490    7628

In [ ]:
# Filtro Peso 1
Autos.loc[Autos.Peso >= 3600 ]    #["Preco"]

Peso    Preco  PesoX2
A4 3.0 Quattro 4dr auto  3627  $34,480    7254
A6 3.0 Quattro 4dr       3880  $39,640    7760
A4 3.0 convertible 2dr   3814  $42,490    7628

In [ ]:
filtro = Autos["Peso"] >= 3600
filtro

A4 3.0 Quattro 4dr manual    False
A4 3.0 Quattro 4dr auto       True
A6 3.0 4dr                   False
A6 3.0 Quattro 4dr            True
A4 3.0 convertible 2dr        True
Name: Peso, dtype: bool

In [ ]:
Autos[filtro]

Peso    Preco  PesoX2
A4 3.0 Quattro 4dr auto  3627  $34,480    7254
A6 3.0 Quattro 4dr       3880  $39,640    7760
A4 3.0 convertible 2dr   3814  $42,490    7628

In [ ]:
# Filtro Peso 2
Autos[Autos["Peso"] >= 3600]

Peso    Preco  PesoX2
A4 3.0 Quattro 4dr auto  3627  $34,480    7254
A6 3.0 Quattro 4dr       3880  $39,640    7760
A4 3.0 convertible 2dr   3814  $42,490    7628

In [ ]:
# Filtro Peso 3
Autos[Autos["Peso"] <  3600]

Peso    Preco  PesoX2
A4 3.0 Quattro 4dr manual  3583  $33,430    7166
A6 3.0 4dr                 3561  $36,640    7122

##--| ==

In [ ]:
Autos["Peso"] == 3627

A4 3.0 Quattro 4dr manual    False
A4 3.0 Quattro 4dr auto       True
A6 3.0 4dr                   False
A6 3.0 Quattro 4dr           False
A4 3.0 convertible 2dr       False
Name: Peso, dtype: bool

In [ ]:
# Filtro Peso 4
Autos[Autos["Peso"] == 3627]

Peso    Preco  PesoX2
A4 3.0 Quattro 4dr auto  3627  $34,480    7254

##--| !=

In [ ]:
# Filtro Peso 4
Autos[Autos["Peso"] != 3627]

Peso    Preco  PesoX2
A4 3.0 Quattro 4dr manual  3583  $33,430    7166
A6 3.0 4dr                 3561  $36,640    7122
A6 3.0 Quattro 4dr         3880  $39,640    7760
A4 3.0 convertible 2dr     3814  $42,490    7628

##--| isin

In [ ]:
# Filtro Peso 4
Autos[Autos["Peso"].isin([3561,3880])]

Peso    Preco  PesoX2
A6 3.0 4dr          3561  $36,640    7122
A6 3.0 Quattro 4dr  3880  $39,640    7760

In [ ]:
# Filtro colunas e linhas loc 1
Autos.loc[Autos["Peso"].isin([3561,3880]), "Preco"]

A6 3.0 4dr            $36,640
A6 3.0 Quattro 4dr    $39,640
Name: Preco, dtype: object

In [ ]:
# Filtro colunas e linhas 2
Autos[Autos["Peso"].isin([3561, 3880])]["Preco"]

A6 3.0 4dr            $36,640
A6 3.0 Quattro 4dr    $39,640
Name: Preco, dtype: object

# Operações no Pandas Transpose


In [ ]:
Autos

Peso    Preco  PesoX2
A4 3.0 Quattro 4dr manual  3583  $33,430    7166
A4 3.0 Quattro 4dr auto    3627  $34,480    7254
A6 3.0 4dr                 3561  $36,640    7122
A6 3.0 Quattro 4dr         3880  $39,640    7760
A4 3.0 convertible 2dr     3814  $42,490    7628

In [ ]:
Autos.T

A4 3.0 Quattro 4dr manual A4 3.0 Quattro 4dr auto A6 3.0 4dr  \
Peso                        3583                    3627       3561   
Preco                    $33,430                 $34,480    $36,640   
PesoX2                      7166                    7254       7122   

       A6 3.0 Quattro 4dr A4 3.0 convertible 2dr  
Peso                 3880                   3814  
Preco             $39,640                $42,490  
PesoX2               7760                   7628

In [ ]:
Autos

Peso    Preco  PesoX2
A4 3.0 Quattro 4dr manual  3583  $33,430    7166
A4 3.0 Quattro 4dr auto    3627  $34,480    7254
A6 3.0 4dr                 3561  $36,640    7122
A6 3.0 Quattro 4dr         3880  $39,640    7760
A4 3.0 convertible 2dr     3814  $42,490    7628

# Operações vetorizadas

In [ ]:
peso   = [3583, 3627, 3561, 3880, 3814]
volume = [10, 5, 45, 32, 15]

Autos_2 = pd.DataFrame({'Peso':peso, 'Volume':volume})
Autos_2

Peso  Volume
0  3583      10
1  3627       5
2  3561      45
3  3880      32
4  3814      15

In [ ]:
Autos_2["Volume"].sum()

np.int64(107)

In [ ]:
Autos_2["Pc_volume"] = (Autos_2["Volume"]/ Autos_2["Volume"].sum())*100
Autos_2

Peso  Volume  Pc_volume
0  3583      10   9.345794
1  3627       5   4.672897
2  3561      45  42.056075
3  3880      32  29.906542
4  3814      15  14.018692

In [ ]:
Autos_2["Peso"]+Autos_2["Volume"]

0    3593
1    3632
2    3606
3    3912
4    3829
dtype: int64

In [ ]:
Autos_2.iloc[:2,]

Peso  Volume  Pc_volume
0  3583      10   9.345794
1  3627       5   4.672897

In [ ]:
Autos_2["Volume"]

0    10
1     5
2    45
3    32
4    15
Name: Volume, dtype: int64

In [ ]:
Autos_2.iloc[:2,]["Peso"]+Autos_2["Volume"]

0    3593.0
1    3632.0
2       NaN
3       NaN
4       NaN
dtype: float64

## Soma comum

In [ ]:
Autos_2["soma"] = Autos_2["Peso"]+Autos_2["Volume"]
Autos_2

Peso  Volume  Pc_volume  soma
0  3583      10   9.345794  3593
1  3627       5   4.672897  3632
2  3561      45  42.056075  3606
3  3880      32  29.906542  3912
4  3814      15  14.018692  3829

## Soma missing

In [ ]:
Autos_2.iloc[:2,]["Peso"]

0    3583
1    3627
Name: Peso, dtype: int64

In [ ]:
Autos_2.iloc[:2,]["Peso"]+Autos_2["Volume"]

0    3593.0
1    3632.0
2       NaN
3       NaN
4       NaN
dtype: float64